name: Approve or Reject Listings

on:
  repository_dispatch:
    types: [approve-listings, reject-listings]

permissions:
  contents: write

jobs:
  handle-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Git pull latest changes
        run: git pull origin main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Extract payload
        run: |
          echo 'EVENT_PAYLOAD<<EOF' >> $GITHUB_ENV
          echo '${{ toJson(github.event.client_payload) }}' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Approve listings
        if: github.event.action == 'approve-listings'
        run: python approve.py

      - name: Reject listings
        if: github.event.action == 'reject-listings'
        run: python reject.py

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add data/
          git commit -m "Update approved/rejected/pending" || echo "No changes"
          git push

      - name: Trigger GitHub Pages rebuild
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-pages-rebuild
