name: Rebuild Pages

on:
  repository_dispatch:
    types: [trigger-pages-rebuild]

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Commit changes to trigger GitHub Pages
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          touch .trigger-pages
          git add .trigger-pages
          git commit -m "Trigger GitHub Pages rebuild" || echo "No changes"
          git push
